name: IPFS Upload Workflow

on:
  workflow_dispatch:

jobs:
  upload-to-ipfs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # rc
      with:
        egress-policy: audit
    
    - name: Checkout repository
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

    - name: Setup IPFS
      uses: ipfs-shipyard/ipfs-github-action@v2
      with:
        ipfs_version: 0.11.0
        run_daemon: true

    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@12cc5d253735dc2894fe19828bd042c8532acc5d # v0.3.1
      with:
        path: ./path/to/your/content
        service: ipfs
        verbose: true
      id: ipfs

    - name: Display IPFS hash
      run: echo "Content uploaded to IPFS with hash ${{ steps.ipfs.outputs.hash }}"

    - name: Create IPFS URL
      run: echo "https://ipfs.io/ipfs/${{ steps.ipfs.outputs.hash }}"
